spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://my_db:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: gke
  cloud:
    gcp:
      sql:
#        instance-connection-name: <PROJECT_ID>:<REGION>:<INSTANCE_NAME> (from ConfigMap)
        database-name: mydb
#        encoded-key: ewogICJ0e...... (from Secret)