apiVersion: batch/v1
kind: Job
metadata:
  name: spring-job-$JOB_NAME
spec:
  template:
    spec:
      serviceAccountName: batch
      restartPolicy: OnFailure
      containers:
        - name: bootiful-job
          image: gcr.io/$PROJECT_NAME/spring-batch:0.0.1
          imagePullPolicy: Always
          args: ["fileName=$FILE_NAME"]
          env:
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: db.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: db.password
